// <auto-generated />
using Legend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Legend.Data.Migrations
{
    [DbContext(typeof(LegendContext))]
    [Migration("20230312194205_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Legend.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Legend.Domain.Entities.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Health = 6,
                            Name = "Gunner",
                            Speed = 6,
                            Stamina = 7,
                            Strength = 5
                        },
                        new
                        {
                            CharacterId = 2,
                            Health = 10,
                            Name = "Defender",
                            Speed = 4,
                            Stamina = 5,
                            Strength = 10
                        },
                        new
                        {
                            CharacterId = 3,
                            Health = 6,
                            Name = "Ninja",
                            Speed = 8,
                            Stamina = 7,
                            Strength = 5
                        },
                        new
                        {
                            CharacterId = 4,
                            Health = 5,
                            Name = "Healer",
                            Speed = 6,
                            Stamina = 6,
                            Strength = 5
                        },
                        new
                        {
                            CharacterId = 5,
                            Health = 7,
                            Name = "Sniper",
                            Speed = 7,
                            Stamina = 7,
                            Strength = 5
                        },
                        new
                        {
                            CharacterId = 6,
                            Health = 7,
                            Name = "Runner",
                            Speed = 10,
                            Stamina = 8,
                            Strength = 5
                        },
                        new
                        {
                            CharacterId = 7,
                            Health = 8,
                            Name = "Ghost",
                            Speed = 8,
                            Stamina = 8,
                            Strength = 7
                        });
                });

            modelBuilder.Entity("Legend.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("InventoryId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            CharacterId = 1,
                            Damage = 5,
                            Name = "Assault rife",
                            Type = "Gun"
                        },
                        new
                        {
                            InventoryId = 2,
                            CharacterId = 2,
                            Damage = 5,
                            Name = "Shotgun",
                            Type = "Gun"
                        },
                        new
                        {
                            InventoryId = 3,
                            CharacterId = 3,
                            Damage = 5,
                            Name = "Katana",
                            Type = "Sword"
                        },
                        new
                        {
                            InventoryId = 4,
                            CharacterId = 5,
                            Damage = 5,
                            Name = "Sniper",
                            Type = "Gun"
                        },
                        new
                        {
                            InventoryId = 5,
                            CharacterId = 6,
                            Damage = 5,
                            Name = "Bowie",
                            Type = "Knife"
                        },
                        new
                        {
                            InventoryId = 6,
                            CharacterId = 7,
                            Damage = 5,
                            Name = "Silenced Sniper",
                            Type = "Gun"
                        },
                        new
                        {
                            InventoryId = 7,
                            CharacterId = 4,
                            Damage = 5,
                            Name = "Health Blaster",
                            Type = "Gun"
                        });
                });

            modelBuilder.Entity("Legend.Domain.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("PlayerId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Legend.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Legend.Domain.Entities.Character", "Character")
                        .WithMany("Inventories")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Legend.Domain.Entities.Player", b =>
                {
                    b.HasOne("Legend.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Legend.Domain.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Legend.Domain.Entities.Character", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
